version: '3.7'

services:
  homozash:
    container_name: homozash
    build: .
    network_mode: bridge
    ports:
      - '7890:7890/tcp'
      - '7890:7890/udp'
      - '7880:80'
      - '9090:9090'
    volumes:
      - ./mihomo:/root/.config/mihomo
      - /dev/net/tun:/dev/net/tun
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
